Initial commit.
hacktoolkit/csharp-htk pull request #1
Opened 2021-10-05 19:42 UTC by gwainor

2021-10-17 01:44 UTC, jontsai requested changes

2021-10-17 01:44 UTC, jontsai commented on csharp-htk/obj/Debug/netstandard2.0/csharp-htk.AssemblyInfo.cs
> +[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
If possible, let's use SemVer (https://semver.org/) and start off with version `0.1.0`

I'm not sure if C# requires 4 numbers; if so, go with `0.1.0.0`

2021-10-17 01:44 UTC, jontsai commented on csharp-htk/Utils/Debug.cs
> +        private const string DEFAULT_FILE_PATH = "debug.log";
filename should be `fdebug.log`

2021-10-17 01:44 UTC, jontsai commented on csharp-htk/obj/Debug/netstandard2.0/HTK.AssemblyInfoInputs.cache
> +62b3153406622242165e51d622b7cc23ee632f9f
Should all of the `.cache` files be removed? Possibly add a `.gitignore` (https://github.com/github/gitignore) file and ignore `*.cache`?

2021-10-17 01:44 UTC, jontsai commented on csharp-htk/obj/Debug/netstandard2.0/HTK.GeneratedMSBuildEditorConfig.editorconfig
> +build_property.ProjectDir = D:\Coding\csharp-htk\csharp-htk\
I think this should potentially be `.gitignore`-d because the giveaway is that `D:\` is a unique path

2021-10-17 01:44 UTC, jontsai commented on csharp-htk/obj/Debug/netstandard2.0/csharp-htk.GeneratedMSBuildEditorConfig.editorconfig
> +build_property.ProjectDir = C:\Users\Gökhan\source\repos\csharp-htk\csharp-htk\
`.gitignore` this

2021-10-17 01:44 UTC, jontsai commented on csharp-htk/obj/HTK.csproj.nuget.g.props
> +﻿<?xml version="1.0" encoding="utf-8" standalone="no"?>
all developer specific-local files should be `.gitignore`-d

2021-10-17 02:21 UTC, jontsai requested changes

2021-10-17 02:21 UTC, jontsai commented on csharp-htk/Utils/Debug.cs
> +        public static void FileDump(string text, string filename = null)
Could we name this `fdebug`?

2021-10-17 02:21 UTC, jontsai commented on csharp-htk/Utils/Debug.cs
> +        /// Sends given text to slack.
`Slack`

2021-10-17 02:21 UTC, jontsai commented on .github/workflows/publish.yml
> +    - "v[0-9]+.[0-9]+.[0-9]+"
Is it possible to use `"v\d+\.\d+\.\d+"` for short? And not sure if the `.` needs to be escaped. I might be wrong...

2021-10-17 02:21 UTC, jontsai commented on README.md
> +- Debug via Slack using `HTK.Utils.Debug.Send`.
Is it possible to make the intermediate module named `Debuggers` instead of `Debug`?

Is the convention for C# static methods to be upper-cased?

Alternate names, in order of preference:

- `slack_debug`
- `SlackDebug`
- `ToSlack`

Alternately, if we go with a module hierarchy like `HTK.Utils.Debuggers.Slack`, the method name could just be `send` or `Send` (prefer lowercase to distinguish the method from the module)

2021-10-17 02:21 UTC, jontsai commented on README.md
> +- Debug via writing to local file using `HTK.Utils.Debug.FileDump`. Certifiably awesome, fast, and secure.
Alternate names, in order of preference:

- `fdebug` (and add an alias `fdb`)
- `FDebug`

Alternately, if we can have the module hierarchy be `HTK.Utils.Debuggers.FileDebug` or `*.FDebug`, then the method could be simply be named `send` or `Send`

2021-10-18 19:34 UTC, Quanthir commented on README.md
> +- Debug via Slack using `HTK.Utils.Debug.Send`.
All namespaces, class names, method names, properties are being CamelCase in C# despite them being static or instanced. But I can make changes if you want.

2021-10-18 20:19 UTC, gwainor reviewed
I have made the necessary changes that you requested.

2021-10-18 20:19 UTC, Quanthir commented on .github/workflows/publish.yml
> +    - "v[0-9]+.[0-9]+.[0-9]+"
I am not sure which regexp library github actions uses. So I did not make any changes. It's possible that it won't recognize it.

2021-10-20 21:23 UTC, closed without merging